5 1 session error complete
likelion-Inha-12/YeomJongSeop pull request #6
Opened 2024-05-06 13:02 UTC by YeomJongSeop

커맨트 덕분에 오류 해결했습니다!! 감사합니다.
migration이 안될때는 지우고 다시 하면 되는 것을 알았습니다. 

<img width="1551" alt="스크린샷 2024-05-06 21 47 04" src="https://github.com/likelion-Inha-12/YeomJongSeop/assets/71175665/b180d9f6-9d25-4162-8fd5-8ead20d0fee2">

<img width="1551" alt="스크린샷 2024-05-06 21 53 00" src="https://github.com/likelion-Inha-12/YeomJongSeop/assets/71175665/199ba542-3e4e-48fd-bb8c-7842db67edef">

2024-05-07 07:12 UTC, kseysh commented
PR올리지 않아도 되는 파일들은 `.gitignore`로 제외하고 다시 한 번 올려주시겠어요~? 80개의 파일을 다 확인하기는 어려워요 ㅠㅠ 그리고 키워드 과제도 해주셔야 합니다!!

2024-05-07 07:13 UTC, kseysh requested changes
PR올리지 않아도 되는 파일들은 .gitignore로 제외하고 다시 한 번 올려주시겠어요~? 80개의 파일을 다 확인하기는 어려워요 ㅠㅠ 그리고 키워드 과제도 해주셔야 합니다!!

2024-05-07 17:23 UTC, YeomJongSeop commented
gitignore가 평소에 적용이 안되어서, 찾아본후 캐시를 초기화 시킨후 새로 커밋해서 불필요한 파일제거했습니다. 키워드 과제도 추가했습니다. 감사합니다.

2024-05-08 07:13 UTC, kseysh requested changes

2024-05-08 07:13 UTC, kseysh commented on django/seminar_project/.gitignore
> +member/
이 폴더는 최상위 폴더에서만 적용됩니다! 최상위 폴더로 변경하고, git 캐시 삭제 다시 진행해주세요!

2024-05-08 08:02 UTC, YeomJongSeop commented on django/seminar_project/.gitignore
> +member/
커멘트 주셔서 불필요한 파일 다 제거 했습니다 감사합니다!

2024-05-08 08:21 UTC, kseysh approved these changes
여러번 요청드리긴 했는데 결국 잘 해주셨네요~! 이번에 git 만져보면서 git과 좀 더 친해지는 계기가 되었다면 좋겠습니다! 수고하셨어요~!

2024-05-08 08:21 UTC, kseysh commented on django/seminar_project/lionapp/views.py
> +    return Response(response, status=status)
실습에서는 Util 앱에 api_response 함수를 만들긴했습니다!

2024-05-08 08:21 UTC, kseysh commented on django/seminar_project/lionapp/views.py
> +        return JsonResponse({'post_list': post_list})
옹 일부러 다른 것도 해보신 건가요~? 좋습니다!!

2024-05-08 08:21 UTC, kseysh commented
그리고 마무리된 PR은 머지해주셔도 됩니다!
머지해주시지 않으면 이전 내역들도 계속 PR에 남아요!

2024-05-08 09:11 UTC, merged